<a href="https://colab.research.google.com/github/Blecyrajan/Welcome-to-user/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [19]:
#please provide your answer below this line.
import numpy as np
x = np.arange(1,10).reshape(3,3)
print("x =",x)
y = np.arange(10,19).reshape(3,3)
print("y =",y)
print("Dot product =",np.dot(x,y))
Dotproduct = np.dot(x,y)
print("Transpose =",np.transpose(Dotproduct))

x = [[1 2 3]
 [4 5 6]
 [7 8 9]]
y = [[10 11 12]
 [13 14 15]
 [16 17 18]]
Dot product = [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
Transpose = [[ 84 201 318]
 [ 90 216 342]
 [ 96 231 366]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [6]:
#please provide your answer below this line.
import numpy as np
A = np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Matrix A =\n",A)
det = np.linalg.det(A)
print("Determinant of A =",int(det))


Matrix A =
 [[55 25 15]
 [30 44  2]
 [11 45 77]]
Determinant of A = 137180
