<a href="https://colab.research.google.com/github/Blecyrajan/Welcome-to-user/blob/main/TASK_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).

In [9]:
#please type your answer below this line.
import numpy as np
A = np.array([[0,1,2],[4,5,6],[7,8,9]])
B = np.array([[10,11,12],[13,14,15],[16,17,18]])
print("Matrices:")
print("A =",A)
print("B =",B) 
print("Outer product of matrices A and B = ")
print(np.outer(A,B)) 
print("Dot product =\n ",np.dot(A,B))
print("Element wise product =\n ",np.multiply(A,B))



Matrices:
A = [[0 1 2]
 [4 5 6]
 [7 8 9]]
B = [[10 11 12]
 [13 14 15]
 [16 17 18]]
Outer product of matrices A and B = 
[[  0   0   0   0   0   0   0   0   0]
 [ 10  11  12  13  14  15  16  17  18]
 [ 20  22  24  26  28  30  32  34  36]
 [ 40  44  48  52  56  60  64  68  72]
 [ 50  55  60  65  70  75  80  85  90]
 [ 60  66  72  78  84  90  96 102 108]
 [ 70  77  84  91  98 105 112 119 126]
 [ 80  88  96 104 112 120 128 136 144]
 [ 90  99 108 117 126 135 144 153 162]]
Dot product =
  [[ 45  48  51]
 [201 216 231]
 [318 342 366]]
Element wise product =
  [[  0  11  24]
 [ 52  70  90]
 [112 136 162]]


2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)

In [ ]:
#please type your answer below this line.
