<a href="https://colab.research.google.com/github/Blecyrajan/Welcome-to-user/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [5]:
#please provide your answer below this line.
import numpy as np
array = np.random.randint(9,size = (3,3))
print(array)


[[3 0 6]
 [7 5 4]
 [7 1 5]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [74]:
#please provide your answer below this line.
import numpy as np
a = np.full((4,4),17)
p = np.full((4,4),34)
print('A = ',a)
print('P = ',p)




A =  [[17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]]
P =  [[34 34 34 34]
 [34 34 34 34]
 [34 34 34 34]
 [34 34 34 34]]


In [86]:
b = a.reshape(2,8)
print(b)

[[17 17 17 17 17 17 17 17]
 [17 17 17 17 17 17 17 17]]


In [87]:
q = p.reshape(2,8)
print(q)


[[34 34 34 34 34 34 34 34]
 [34 34 34 34 34 34 34 34]]


In [88]:
np.vstack((b,q))

array([[17, 17, 17, 17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17, 17, 17, 17],
       [34, 34, 34, 34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34, 34, 34, 34]])

In [89]:
np.hstack((b,q))

array([[17, 17, 17, 17, 17, 17, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34],
       [17, 17, 17, 17, 17, 17, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34]])